Remove filter negate
open-telemetry/opentelemetry-go-contrib pull request #2672
Opened 2022-08-16 20:13 UTC by Jthomas54

While attempting to use the new filter from #2572, I noticed that the `HealthCheck` filter still recorded spans even though it was meant to filter them out.  I believe it stemmed from a code suggestion that changed the methods name, but not the related logic.

I update the tests as best I could.

2022-08-16 21:03 UTC, dashpole commented
cc @ymotongpoo

2022-08-16 21:30 UTC, Aneurysm9 requested changes
I think the issue is actually that the comment didn't get updated. The implementation is correct and the `HealthCheck()` filter should return `true` for health checks and cause them to be instrumented.  Use `Not(HealthCheck())` to exclude them.

2022-08-17 00:39 UTC, ymotongpoo commented
@Aneurysm9 yes, I forgot to update the comment!

@Jthomas54 the behavior is correct and the comment for HealthCheck is written in opposite way. It should be:

```
// HealthCheck returns a Filter that returns true if the request's
// is health check defined by gRPC Health Checking Protocol.
// https://github.com/grpc/grpc/blob/master/doc/health-checking.md
```

Removing "not" from the comment should work.

2022-08-17 01:12 UTC, Jthomas54 commented
Ah, didn't realize there was a `Not` option.  Perhaps this isn't the best place to ask, but if you'll indulge me a second.  The purpose of the filter is to stop the otelgrpc interceptor for creating a span correct?  If that is the case, it seems odd that any filter wouldn't appear to work without first passing it through the `Not` option.  I think is is probably more a question of API design rather than function perhaps.

2022-08-17 01:34 UTC, ymotongpoo commented
> The purpose of the filter is to stop the otelgrpc interceptor from creating a span correct?

You can use filter for that purpose (and I implemented the gRPC one for that purpose) but the intention of `otelgrpc.Filter` is opposite. It is the option to intercept spans that apply to the filter, which is consistent with [`otelhttp.Filter`](https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp#Filter)

> If that is the case, it seems odd that any filter wouldn't appear to work without first passing it through the Not option.

That is the reason why `cfg.Filter != nil` is the first condition. The default is to intercept all spans.

2022-08-17 01:42 UTC, Jthomas54 commented
Background helps!  Thanks, closing.

2022-08-17 01:42 UTC, closed without merging