fix otelhttp client span end
open-telemetry/opentelemetry-go-contrib pull request #3873
Opened 2023-05-22 04:05 UTC by mjlzz

Issue: otelhttp client does not end span when err is nil, users will not get the right spans
This PR fix the issue

2023-05-22 06:08 UTC, pellared requested changes
What are the repro steps?

The span ends when the caller closes the request body. https://github.com/open-telemetry/opentelemetry-go-contrib/blob/8850f949daf5fe8a1906fe395d23937c2b417c67/instrumentation/net/http/otelhttp/transport.go#L188

2023-05-22 07:14 UTC, mjlmton commented
please close the PR.
it seems like I did not handle the response in the right way,  wrong code like below:
`_, err := client.Do(req)`
`if err != nil {`
`        panic(err)`
`}`
this leave a question: if user don't need to handle response, they still should close response manually, right?

2023-05-22 07:32 UTC, closed without merging

2023-05-22 07:34 UTC, dmathieu commented
Yes, you must always close the response after dealing with it. But that's not something required by otelhttp, it's something required by Go.

https://pkg.go.dev/net/http

> The client must close the response body when finished with it

2023-08-19 09:49 UTC, schmurfy commented
I just stumbled on this and while closing the body is indeed required by go to avoid leaks the behaviour should be documented somewhere.

2023-08-19 12:18 UTC, dmathieu commented
Here for example?
https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp#Transport.RoundTrip