Migration from `github.com/Shopify/sarama` to `github.com/IBM/sarama`
open-telemetry/opentelemetry-go-contrib pull request #4090
Opened 2023-07-17 21:18 UTC by batazor

2023-07-17 21:53 UTC, batazor commented
I think I've updated all the necessary places.

2023-07-17 23:20 UTC, MrAlias requested changes
It is unclear we would want to change our package name to match the upstream redirect. If we did end up wanting to do so, it will require a deprecation of the existing package.

2023-07-18 08:13 UTC, pellared commented
@batazor Can the new instrumentation library be https://github.com/IBM/sarama or new repository e.g. https://github.com/IBM/otelsarama?

2023-07-18 14:33 UTC, MrAlias commented on CODEOWNERS
> +instrumentation/github.com/IBM/sarama/otelsarama/                       @open-telemetry/go-approvers @pellared @hanyuancheung
```suggestion
instrumentation/github.com/Shopify/sarama/otelsarama/                   @open-telemetry/go-approvers @pellared @hanyuancheung
```

2023-07-18 14:33 UTC, MrAlias commented on CHANGELOG.md
> +- Migration from `github.com/Shopify/sarama` to `github.com/IBM/sarama`
```suggestion
- Updated dependency of `github.com/Shopify/sarama` in `go.opentelemetry.io/contrib/instrumentation/github.com/IBM/sarama/otelsarama` to `github.com/IBM/sarama` so as to match the upstream package rename. (#4090)
```

2023-07-18 18:05 UTC, MrAlias approved these changes

2023-07-18 19:05 UTC, XSAM approved these changes

2023-07-19 08:55 UTC, pellared commented
I created https://github.com/IBM/sarama/issues/2510.

2023-07-19 08:56 UTC, hanyuancheung approved these changes

2023-07-19 10:36 UTC, pellared commented
> It is unclear we would want to change our package name to match the upstream redirect. If we did end up wanting to do so, it will require a deprecation of the existing package.

> I left only changing the path to the dependency, don't change the path in this package, this will save the working state of observability

I would rather change the package name to match upstream redirect as the users already need to change the import paths for the library 😉

2023-07-19 10:39 UTC, dmathieu commented
I agree that if we end up keeping this instrumentation, we should rename the package as well.
Ideally, now would be a good time to move it into a better location though.

2023-07-19 10:42 UTC, pellared requested changes
Blocking mainly because of https://github.com/open-telemetry/opentelemetry-go-contrib/pull/4090#issuecomment-1641843514 but also awaiting feedback under https://github.com/IBM/sarama/issues/2510

2023-07-19 14:16 UTC, MrAlias commented
I don't think the question of renaming this package should block the update of the dependency.

2023-07-19 18:55 UTC, Aneurysm9 reviewed
I'm not sure it's appropriate to simply change the dependency here.  Won't that break anyone still using the prior import paths who updates this instrumentation?  Should we deprecate this instrumentation?  New instrumentation for the new import path can be created, ideally owned by the sarama maintainers, but anywhere really.

2023-07-19 18:55 UTC, Aneurysm9 commented on instrumentation/README.md
> +|                                   [runtime](./runtime)                                   |    ✓    |        |
Please, no.

2023-07-19 18:59 UTC, MrAlias commented
> I'm not sure it's appropriate to simply change the dependency here. Won't that break anyone still using the prior import paths who updates this instrumentation?

Good point.

2023-07-21 12:06 UTC, pellared commented
Closing as there is no consensus to ONLY update the dependency using the new import path.

2023-07-21 12:06 UTC, closed without merging