Remove high cardanility metrics from otelhttp
open-telemetry/opentelemetry-go-contrib pull request #4277
Opened 2023-09-05 19:46 UTC by MadVikingGod

This does not upgrade to the latest semantic convention, that will be a different PR.

This removes the following attributes from the metrics that `go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp` generates:
- `net.sock.peer.addr`
- `net.sock.peer.port`
- `http.user_agent`
- `enduser.id`
- `http.client_ip`

This also only allows `http.request.method` to be known HTTP methods, or `_OTHER`.

2023-09-06 03:36 UTC, hanyuancheung approved these changes

2023-09-06 07:51 UTC, pellared commented on instrumentation/github.com/gin-gonic/gin/otelgin/internal/semconvutil/httpconv.go
> +	}
This looks very Pythonish 😉 

How about using `switch` and constants from `http` package?

```go
	switch method {
	case http.MethodGet , http.MethodHead, http.MethodPost, ....
	default:
		method = "_OTHER"
	}
```

2023-09-06 15:42 UTC, MadVikingGod commented on instrumentation/github.com/gin-gonic/gin/otelgin/internal/semconvutil/httpconv.go
> +	method = strings.ToUpper(method)
The semantic convention has a list of values allowed, and we are to convert equivalent levels into the canonical form.  If this were tracing, where we don't have cardinality concerns, we would also set `http.request.method_original`. https://github.com/open-telemetry/semantic-conventions/blob/main/model/http-common.yaml

2023-09-06 17:10 UTC, pellared commented on instrumentation/github.com/emicklei/go-restful/otelrestful/internal/semconvutil/httpconv.go
> +func (c *httpConv) ServerRequestMetrics(server string, req *http.Request) []attribute.KeyValue {
I think you should also create a `HTTPServerRequestMetrics` function (that will be used in `otelhttp`) and add tests.

2023-09-06 17:12 UTC, pellared commented on instrumentation/github.com/gin-gonic/gin/otelgin/internal/semconvutil/httpconv.go
> +	method = strings.ToUpper(method)
Thanks for clarification.

2023-09-07 09:41 UTC, pellared approved these changes

2023-09-07 09:45 UTC, pellared requested changes

2023-09-07 09:45 UTC, pellared commented on internal/shared/semconvutil/httpconv.go.tmpl
> +// "http.client_ip".
```suggestion
// The following attributes are always returned: "http.method", "http.scheme",
// "http.flavor", "net.host.name". The following attributes are
// returned if they related values are defined in req: "net.host.port".
```

2023-09-07 09:45 UTC, pellared commented on internal/shared/semconvutil/httpconv.go.tmpl
> +// ServerRequestMetrics returns Metric attributes for an HTTP request received
```suggestion
// ServerRequestMetrics returns metric attributes for an HTTP request received
```

2023-09-07 09:45 UTC, pellared commented on internal/shared/semconvutil/httpconv.go.tmpl
> +// HTTPServerRequestMetrics returns trace attributes for an HTTP request received by a
```suggestion
// HTTPServerRequestMetrics returns metrics attributes for an HTTP request received by a
```

2023-09-07 16:45 UTC, pellared approved these changes

2023-09-07 17:18 UTC, merged

2023-09-12 05:16 UTC, davendu commented
Weird. Why @dmathieu 's [previous suggestion](https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3980#pullrequestreview-1476833100) is not applied to this PR:

> I don't think this is the proper approach. It's adding some weird complexity, and whether an attribute has too much cardinality or not is very subjective.
> 
> The solution being discussed in [open-telemetry/opentelemetry-specification#3061](https://github.com/open-telemetry/opentelemetry-specification/issues/3061) seems much better.


And what's the community's suggestion towards similar attributes? My own instrumentation library also needs some `high cardanility` attributes, and not sure if I should remove them or filter through the view.

2023-09-12 07:11 UTC, dmathieu commented
This PR solves from a potential memory leak issue, since the values from those attributes are coming from untrusted sources.
We should be able to bring back those attributes once something like https://github.com/open-telemetry/opentelemetry-go/pull/4457 is stable.

2023-09-12 10:55 UTC, FaranIdo commented
@dmathieu @pellared @MadVikingGod  do you plan to add a similar solution to otelgrpc to avoid high cardinality there as well? (I think reported here: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/3071)