Add span start end end options to gin configuration
open-telemetry/opentelemetry-go-contrib pull request #5250
Opened 2024-03-06 13:37 UTC by dmathieu

This allows setting span start and end options to the gin configuration, so folks can (for example), enable stack traces to recorded errors.

Closes #5139.

2024-03-06 13:39 UTC, dmathieu commented on instrumentation/github.com/gin-gonic/gin/otelgin/gintrace.go
> +		defer span.End(cfg.SpanEndOptions...)
I didn't write a test for this, as the only option is `WithStackTrace`, and I could only trigger it with a `panic()`, which wouldn't really allow a test.

2024-03-06 14:48 UTC, dmathieu commented on instrumentation/github.com/gin-gonic/gin/otelgin/test/gintrace_test.go
> +func TestWithSpanStartOptions(t *testing.T) {
See my comment here: https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5250#discussion_r1514502545

2024-03-12 10:49 UTC, dmathieu commented on instrumentation/github.com/gin-gonic/gin/otelgin/test/gintrace_test.go
> +func TestWithSpanStartOptions(t *testing.T) {
I have added one with `trace.WithTimestamp`.

2024-03-27 09:22 UTC, pellared requested changes
Similarly to https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5251#pullrequestreview-1962694859

> The user can e.g. change the span kind using https://pkg.go.dev/go.opentelemetry.io/otel/trace#WithSpanKind or create attributes which are not aligned with the semantic conventions and they others may blame that the instrumentation library does not follow semantic conventions.

However, with the difference that `func HTML(c *gin.Context, code int, name string, obj interface{}) {` is calling `span.RecordError(err)` when `c.HTML(code, name, obj)` panics.

Maybe we should just add an option to capture stacktraces instead?

2024-04-03 10:26 UTC, closed without merging