Use SingleHeader format for unspecified B3 inject encoding
open-telemetry/opentelemetry-go-contrib pull request #614
Opened 2021-03-13 07:37 UTC by gunturaf

**Which problem is this PR solving?**

This PR changes default behavior when B3 inject encoding is unspecified from multi-header to single-header, per #613.

**Short description of the changes**

- Use single-header format when B3 inject encoding is unspecified
- Modify test data for cases involving unspecified B3 inject encoding

2021-03-16 15:44 UTC, MrAlias requested changes

2021-03-16 15:44 UTC, MrAlias commented on propagators/b3/b3_data_test.go
>  			b3ParentSpanID,
Ensure this is single header now as well.

```suggestion
			b3ParentSpanID,
			b3TraceID,
			b3SpanID,
			b3Sampled,
```

2021-03-16 15:44 UTC, MrAlias commented on propagators/b3/b3_data_test.go
>  			b3ParentSpanID,
```suggestion
			b3ParentSpanID,
			b3TraceID,
			b3SpanID,
			b3Sampled,
```

2021-03-16 15:44 UTC, MrAlias commented on propagators/b3/b3_data_test.go
>  			b3Sampled,
```suggestion
			b3Sampled,
			b3TraceID,
			b3SpanID,
```

2021-03-16 15:44 UTC, MrAlias commented on propagators/b3/b3_data_test.go
>  			b3Sampled,
```suggestion
			b3Sampled,
			traceIDStr,
			spanIDStr,
```

2021-03-16 15:44 UTC, MrAlias commented on propagators/b3/b3_data_test.go
>  			b3Sampled,
```suggestion
			b3Sampled,
			traceIDStr,
			spanIDStr,
			b3Flags,
```

2021-03-17 15:01 UTC, MrAlias approved these changes

2021-03-18 15:11 UTC, Aneurysm9 approved these changes

2021-03-18 15:11 UTC, merged