feat: add LogProcessor to baggagecopy
open-telemetry/opentelemetry-go-contrib pull request #6277
Opened 2024-10-26 01:22 UTC by Jesse0Michael

add a Log Record Processor to the baggagecopy package that copies members from baggage and adds them to the log record attributes.

---

mimics the `baggagecopy` Span Processor, that copies filtered baggage members from the parent span's context and adds them as span attributes, and instead filters baggage members from the log processor OnEmit context and adds them to the log record as attributes.

followed the prior art of the existing Span Processor closely to include baggage in logs.

2024-10-28 08:35 UTC, dmathieu commented
cc @MikeGoldsmith as code owner.

2024-10-28 08:51 UTC, pellared approved these changes

2024-10-28 08:51 UTC, pellared commented on processors/baggagecopy/doc.go
> +// emitting the log dds them as attributes to the log.
```suggestion
// emitting the log and adds them as attributes to the log.
```

2024-10-28 08:52 UTC, pellared commented
> cc @MikeGoldsmith as code owner.

Also CC @codeboten

2024-10-28 15:43 UTC, MrAlias commented on processors/baggagecopy/log_processor_test.go
> +	// create log provider with the baggage log processor and a log processor used to capture emitted record
```suggestion
```

2024-10-28 15:43 UTC, MrAlias commented on processors/baggagecopy/log_processor_test.go
> +	// log a test record
```suggestion
```

2024-10-28 15:43 UTC, MrAlias commented on processors/baggagecopy/log_processor_test.go
> +	// create log provider with the baggage log processor and a log processor used to capture emitted record
```suggestion
```

2024-10-28 15:43 UTC, MrAlias commented on processors/baggagecopy/log_processor_test.go
> +	// log a test record
```suggestion
```

2024-10-28 15:43 UTC, MrAlias commented on processors/baggagecopy/log_processor_test.go
> +	// create log provider with the baggage log processor and a log processor used to capture emitted record
```suggestion
```

2024-10-28 15:43 UTC, MrAlias commented on processors/baggagecopy/log_processor_test.go
> +	// log a test record
```suggestion
```

2024-10-28 15:43 UTC, MrAlias commented on processors/baggagecopy/log_processor_test.go
> +	// create log provider with the baggage log processor and a log processor used to capture emitted record
```suggestion
```

2024-10-28 15:43 UTC, MrAlias commented on processors/baggagecopy/log_processor_test.go
> +	// log a test record
```suggestion
```

2024-10-28 15:43 UTC, MrAlias commented on processors/baggagecopy/log_processor_test.go
> +func TestLogProcessorAppendsBaggageAttributesWithHaPrefixPredicate(t *testing.T) {
```suggestion
func TestLogProcessorAppendsBaggageAttributesWithHasPrefixPredicate(t *testing.T) {
```

2024-10-28 15:43 UTC, MrAlias commented on processors/baggagecopy/log_processor_test.go
These tests share a lot of the same code. Can the common parts be refactored into a unified code path?

2024-10-29 05:33 UTC, Jesse0Michael commented on processors/baggagecopy/log_processor_test.go
Refactored the tests to be written in a table-driven style.

my original intention was to follow https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/processors/baggagecopy/processor_test.go closely, but maybe this is closer to what you are thinking about. 

LMK if you had something different in mind!

2024-10-29 08:00 UTC, dmathieu approved these changes

2024-11-04 14:19 UTC, MikeGoldsmith requested changes
Overall looks goof to me.

I've left one suggestion about setting the default filter in the `NewLogProcessor` instead of `OnEmit`.

2024-11-04 15:17 UTC, MrAlias commented on processors/baggagecopy/log_processor.go
> +	filter := processor.filter
I think we want to guard against zero value use. Having the filter check here, similar to the span processor, seems appropriate.

2024-11-04 19:17 UTC, MikeGoldsmith approved these changes

2024-11-05 06:08 UTC, merged