replaces golint by revive and fix newly reported linter issues
open-telemetry/opentelemetry-go-contrib pull request #800
Opened 2021-05-23 18:14 UTC by AndersonQ

As [`golint` is deprecated](https://github.com/golang/go/issues/38968) this PR replaces `golint` by [`revive`](https://github.com/mgechev/revive#revive), a drop-in replacement for `golint` and also the one suggested by [`golangci-lint `](https://github.com/golangci/golangci-lint).
It's a followup on #792, closes #792 and relates to #1935

Even though `revive` is a drop-in replacement for `golint` one new lint issues rose after the change. I could not get golint to report it as well, anyway I fixed it.

2021-05-23 20:29 UTC, pellared approved these changes

2021-05-23 20:29 UTC, pellared commented on CHANGELOG.md
> +- Replaces [_golint_](https://github.com/golang/lint) with [_revive_](https://github.com/mgechev/revive)
Personally, I think it is not worth putting it in the changelog. It is purely internal.

2021-05-24 11:46 UTC, dashpole approved these changes

2021-05-26 17:17 UTC, MrAlias requested changes
Please add fixes for all the lint issues:

```
golangci-lint in .
golangci-lint in ./detectors/aws
golangci-lint in ./detectors/aws/ecs
ecs.go:30:2: exported: exported const TypeStr should have comment (or a comment on this block) or be unexported (revive)
	TypeStr           = "ecs"
	^
golangci-lint in ./detectors/aws/eks
golangci-lint in ./detectors/gcp
golangci-lint in ./exporters/metric/cortex
golangci-lint in ./exporters/metric/cortex/example
golangci-lint in ./exporters/metric/cortex/utils
golangci-lint in ./exporters/metric/datadog
golangci-lint in ./exporters/metric/dogstatsd
internal/statsd/conn.go:94:2: exported: exported var ErrInvalidScheme should have comment or be unexported (revive)
	ErrInvalidScheme = fmt.Errorf("invalid statsd transport")
	^
golangci-lint in ./instrumentation/github.com/astaxie/beego/otelbeego
beego.go:29:1: exported: comment on exported type Handler should be of the form "Handler ..." (with optional leading article) (revive)
// OTelBeegoHandler implements the http.Handler interface and provides
// trace and metrics to beego web apps.
golangci-lint in ./instrumentation/github.com/astaxie/beego/otelbeego/example
golangci-lint in ./instrumentation/github.com/aws/aws-sdk-go-v2/otelaws
attributes.go:20:2: exported: exported const OperationKey should have comment (or a comment on this block) or be unexported (revive)
	OperationKey attribute.Key = "aws.operation"
	^
golangci-lint in ./instrumentation/github.com/aws/aws-sdk-go-v2/otelaws/example
golangci-lint in ./instrumentation/github.com/bradfitz/gomemcache/memcache/otelmemcache
golangci-lint in ./instrumentation/github.com/bradfitz/gomemcache/memcache/otelmemcache/example
golangci-lint in ./instrumentation/github.com/emicklei/go-restful/otelrestful
golangci-lint in ./instrumentation/github.com/emicklei/go-restful/otelrestful/example
golangci-lint in ./instrumentation/github.com/gin-gonic/gin/otelgin
golangci-lint in ./instrumentation/github.com/gin-gonic/gin/otelgin/example
golangci-lint in ./instrumentation/github.com/gocql/gocql/otelgocql
golangci-lint in ./instrumentation/github.com/gocql/gocql/otelgocql/example
golangci-lint in ./instrumentation/github.com/go-kit/kit/otelkit
golangci-lint in ./instrumentation/github.com/go-kit/kit/otelkit/example
golangci-lint in ./instrumentation/github.com/gorilla/mux/otelmux
golangci-lint in ./instrumentation/github.com/gorilla/mux/otelmux/example
golangci-lint in ./instrumentation/github.com/labstack/echo/otelecho
golangci-lint in ./instrumentation/github.com/labstack/echo/otelecho/example
golangci-lint in ./instrumentation/github.com/Shopify/sarama/otelsarama
golangci-lint in ./instrumentation/github.com/Shopify/sarama/otelsarama/example
init.go:27:2: exported: exported const KafkaTopic should have comment (or a comment on this block) or be unexported (revive)
	KafkaTopic = "sarama-instrumentation-example"
	^
golangci-lint in ./instrumentation/go.mongodb.org/mongo-driver/mongo/otelmongo
db.go:20:2: exported: exported const DBApplicationKey should have comment (or a comment on this block) or be unexported (revive)
	DBApplicationKey = attribute.Key("db.application")
	^
peer.go:20:2: exported: comment on exported const PeerHostnameKey should be of the form "PeerHostnameKey ..." (revive)
	// PeerHostname records the host name of the peer.
	^
peer.go:22:2: exported: comment on exported const PeerPortKey should be of the form "PeerPortKey ..." (revive)
	// PeerPort records the port number of the peer.
	^
tags.go:20:2: exported: exported const TargetHostKey should have comment (or a comment on this block) or be unexported (revive)
	TargetHostKey  = attribute.Key("out.host")
	^
golangci-lint in ./instrumentation/google.golang.org/grpc/otelgrpc
golangci-lint in ./instrumentation/google.golang.org/grpc/otelgrpc/example
golangci-lint in ./instrumentation/gopkg.in/macaron.v1/otelmacaron
golangci-lint in ./instrumentation/gopkg.in/macaron.v1/otelmacaron/example
golangci-lint in ./instrumentation/host
host.go:72:2: exported: exported var AttributeCPUTimeUser should have comment or be unexported (revive)
	AttributeCPUTimeUser   = []attribute.KeyValue{attribute.String("state", "user")}
	^
golangci-lint in ./instrumentation/host/example
golangci-lint in ./instrumentation/net/http/httptrace/otelhttptrace
clienttrace.go:34:2: exported: exported var HTTPStatus should have comment or be unexported (revive)
	HTTPStatus     = attribute.Key("http.status")
	^
httptrace.go:52:1: exported: comment on exported function Extract should be of the form "Extract ..." (revive)
// Returns the Attributes, Context Entries, and SpanContext that were encoded by Inject.
^
api.go:23:1: exported: comment on exported function W3C should be of the form "W3C ..." (revive)
// Client
^
golangci-lint in ./instrumentation/net/http/httptrace/otelhttptrace/example
golangci-lint in ./instrumentation/net/http/otelhttp
labeler.go:38:1: exported: comment on exported method Labeler.Get should be of the form "Get ..." (revive)
// Labels returns a copy of the attributes added to the Labeler.
^
golangci-lint in ./instrumentation/net/http/otelhttp/example
golangci-lint in ./instrumentation/runtime
runtime.go:153:2: if-return: redundant if ...; err != nil check, just return error instead. (revive)
	if err := r.registerMemStats(); err != nil {
		return err
	}
golangci-lint in ./instrumentation/runtime/example
golangci-lint in ./propagators
golangci-lint in ./propagators/aws
golangci-lint in ./propagators/opencensus
golangci-lint in ./propagators/opencensus/examples
```

2021-05-26 21:53 UTC, MadVikingGod approved these changes

2021-06-08 16:16 UTC, MrAlias approved these changes

2021-06-08 16:30 UTC, merged